module.exports = [
  'Message deletion',
  'Role creation',
  'Role deletion',
  'Bulk deletes',
  'Member leaves',
  'Member joins',
  'Member banned',
  'Member unbaned',
  'Emoji creation',
  'Emoji deletion',
  'Channel creation',
  'Channel deletion',
  'Message edits',
  'Emoji updates',
  'Role given',
  'Role removal',
  'Nickname change',
  'User changes',
  'Voice channel changes',
  'Status changes',
  'Message reactions',
];